#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
printenv

VCS_REF=$(git rev-parse --short HEAD)

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF="$VCS_REF" -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
