#!/usr/bin/env sh

echo "------ HOOK START - POST_PUSH -------"
printenv

if [ "$SOURCE_BRANCH" = 'master' ]; then
  ./scripts/docker.sh tag
fi
./scripts/docker.sh notify
echo "------ HOOK END - POST_PUSH -------"
