#!/usr/bin/env bash

echo "------ HOOK START - POST_PUSH -------"
printenv
export DEBUG=true
export MICROBADGER_URL='https://hooks.microbadger.com/images/vladgh/testautobuildhooks/s4syH8TyWagZghflrtWCpnBKAAs='
~/vgs/scripts/docker.sh notify
echo "------ HOOK END - POST_PUSH -------"
