#!/usr/bin/env bash

echo "------ HOOK START - PRE_BUILD -------"
printenv
apt-get -qy update && apt-get -qy install ruby
ruby --version
gem install --no-ri --no-rdoc bundler
(
  cd ../
  bundle install --without development --path vendor/bundle
)
gem list
echo "------ HOOK END - PRE_BUILD -------"
