#!/usr/bin/env bash

echo "------ HOOK START - PRE_BUILD -------"
printenv
apt-get -qy update && apt-get -qy install ruby
ruby --version
gem list
bundle --version
echo "------ HOOK END - PRE_BUILD -------"
