#!/usr/bin/env bash

docker --version

apt-get -qy update && apt-get -qy install docker-ce
# apt-get -qy update && apt-get -qy install wget

# mkdir -p ~/.docker/cli-plugins
# wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
# chmod a+x ~/.docker/cli-plugins/docker-buildx

# echo "------ HOOK START - PRE_BUILD -------"
# set -euo pipefail
# IFS=$'\n\t'

# printenv

# VGS
# git clone https://github.com/vghn/vgs.git ~/vgs

# RUBY
# apt-get -qy update && apt-get -qy install ruby
# ruby --version
# gem install --no-ri --no-rdoc bundler
# (
#   cd ../  || exit
#   bundle install --without development --path vendor/bundle
# )
# gem list
# echo "------ HOOK END - PRE_BUILD -------"
