#!/usr/bin/env bash

echo "------ HOOK START - PUSH -------"
set -euo pipefail
IFS=$'\n\t'

printenv

export DEBUG=true
if [[ "$DOCKER_TAG" == 'latest' ]]; then
  ~/vgs/scripts/docker.sh push
fi
if [[ "$SOURCE_BRANCH" =~ ^v[0-9]+ ]]; then
  ~/vgs/scripts/docker.sh tag
fi
echo "------ HOOK END - PUSH -------"
