name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-latest-docker-image:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag 'vladgh/testautobuildhooks:latest'
      - name: Push
        run: docker push 'vladgh/testautobuildhooks:latest'
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
