name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}"
      - name: Install BuildX
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build the image
        run: |
          echo "$GIT_TAG"
          docker buildx build --rm --pull --push \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 \
            --tag vladgh/testautobuildhooks:latest \
            --tag vladgh/testautobuildhooks:$(date +%s) \
            .
